In [25]:
#import packages 

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
import torch  
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split


In [26]:
# load the data set "bonus.csv" into a pandas DataFrame

df_bonus = pd.read_csv("bonus.csv")

df_bonus.head()


,employee_id,performance,years_of_experience,projects_completed,bonus
0,EMP_001,7,1,3,116
1,EMP_002,4,8,10,136
2,EMP_003,8,4,5,150
3,EMP_004,5,4,7,118
4,EMP_005,7,5,6,146


In [27]:
#check the rows and colums

df_bonus.shape

(1000, 5)

In [28]:
# train and test and split

X = df_bonus.drop(['bonus','employee_id'], axis=1) # features 
y = df_bonus['bonus'] # target variable

train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.2, random_state=42)



In [29]:
train_X.shape , test_X.shape, train_y.shape, test_y.shape

((800, 3), (200, 3), (800,), (200,))

In [30]:
train_X

,performance,years_of_experience,projects_completed
29,4,3,6
535,2,4,5
695,7,3,5
557,7,8,9
836,6,3,6
...,...,...,...
106,3,1,3
270,4,3,5
860,2,9,12
435,1,9,11


In [31]:
train_X.values

array([[ 4,  3,  6],
       [ 2,  4,  5],
       [ 7,  3,  5],
       ...,
       [ 2,  9, 12],
       [ 1,  9, 11],
       [ 7, 10, 12]], shape=(800, 3))

In [32]:
train_X_tensor = torch.tensor(train_X.values, dtype=torch.float32)
train_y_tensor = torch.tensor(train_y.values, dtype=torch.float32)
test_X_tensor = torch.tensor(test_X.values, dtype=torch.float32)
test_y_tensor = torch.tensor(test_y.values, dtype=torch.float32)

In [33]:
# https://docs.pytorch.org/docs/2.14/generated/torch.nn.Module.html

class BonusModel(nn.Module):
          def __init__(self):
                    super().__init__()
                    self.network = nn.Sequential(
                            nn.Linear(3, 1),  # 3 input features to 1 output
                    )
          def forward(self, x): # X - is input data, x is the input tensor
                    
                    return self.network(x)
          
          


In [34]:
model = BonusModel()
criterion = nn.MSELoss()  # Mean Squared Error loss for regression
optimizer  = optim.Adam(model.parameters(), lr=0.01)  # Adam optimizer

In [42]:
train_X_tensor[0]

tensor([4., 3., 6.])

In [41]:
epochs = 5000
for epoch in range(epochs):
          # 1 - Forward pass
          predictions  = model(train_X_tensor) # intrenall call fowrad method in BonusModel class
          loss = criterion(predictions.squeeze(), train_y_tensor)
          
          # 2-  Backward pass and optimization
          optimizer.zero_grad()
          loss.backward()
          optimizer.step()
          
          if (epoch+1) % 500 == 0:
                    print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}')

Epoch [500/5000], Loss: 0.0000
Epoch [1000/5000], Loss: 0.0000
Epoch [1500/5000], Loss: 0.0000
Epoch [2000/5000], Loss: 0.0000
Epoch [2500/5000], Loss: 0.0000
Epoch [3000/5000], Loss: 0.0000
Epoch [3500/5000], Loss: 0.0000
Epoch [4000/5000], Loss: 0.0000
Epoch [4500/5000], Loss: 0.0000
Epoch [5000/5000], Loss: 0.0000


In [44]:
model.eval()  # Set the model to evaluation mode
with torch.no_grad():  # Disable gradient calculation for inference
          test_predictions = model(test_X_tensor)
          test_loss = criterion(test_predictions.squeeze(), test_y_tensor)
          print(f'Test Loss: {test_loss.item():.4f}')

Test Loss: 0.0000


In [46]:
test_X_tensor[:3]

tensor([[5., 1., 3.],
        [8., 1., 4.],
        [4., 2., 3.]])

In [45]:
test_predictions[:3]

tensor([[ 92.],
        [130.],
        [ 86.]])

In [47]:
# w1, w2, w3 and bias

from anyio import value


for name, value in model.named_parameters():
          print(f"{name}: {value.data.numpy()}")

network.0.weight: [[12.  6.  2.]]
network.0.bias: [20.000002]
