In [35]:
import torch

In [36]:
## Check my cuda (available GPU pytorch)

torch.cuda.is_available() # True = yes, it is available , else false

True

In [37]:
torch.tensor(9)

tensor(9)

In [38]:
revenue = torch.tensor([100,120,90,87,65])

revenue

tensor([100, 120,  90,  87,  65])

In [39]:
## Sales data fro Quarter 1 matrxi 
q1 = torch.tensor([
          [200,220,250],
          [150,180,210],
          [300,330,360]
]
)

q2 = torch.tensor([
          [209,231,259] ,
          [155,192,222],
          [310,340,375]
]
)

q1+q2

tensor([[409, 451, 509],
        [305, 372, 432],
        [610, 670, 735]])

In [40]:
q2-q1

tensor([[ 9, 11,  9],
        [ 5, 12, 12],
        [10, 10, 15]])

In [41]:
(q2-q1) * 100 /q1

tensor([[4.5000, 5.0000, 3.6000],
        [3.3333, 6.6667, 5.7143],
        [3.3333, 3.0303, 4.1667]])

In [42]:
return_rate = 01.

return_rate * q1

tensor([[200., 220., 250.],
        [150., 180., 210.],
        [300., 330., 360.]])

In [43]:
## Profit per unit is given product and region wise
# calcuate total profit for all units per region , per product

profit_per_unit = torch.tensor([
          [30,27,25],
          [20,18,17],
          [45,38,39]
])

profit_per_unit * q1

tensor([[ 6000,  5940,  6250],
        [ 3000,  3240,  3570],
        [13500, 12540, 14040]])

In [44]:
if torch.cuda.is_available():
          device = torch.device("cuda")
else :
        device = torch.device("cpu")
        

In [45]:
device

device(type='cuda')

In [46]:
# Simulating customer data with 1 million customers and 3 featuires (age, spedning score , income)

customer_data = torch.rand(1_000_000, 3 ,device=device)

customer_data.shape

torch.Size([1000000, 3])

In [47]:
# let me check the top 3 rows from the matrix 

customer_data[:3,]

tensor([[0.3020, 0.0810, 0.3185],
        [0.3304, 0.8016, 0.8729],
        [0.7222, 0.2612, 0.0339]], device='cuda:0')

In [48]:
# I want to ge the all rows where spending score is more than 0.5


high_spending_score = customer_data[customer_data[:,1] > 0.5] # all rows and secodn columns 

In [49]:
high_spending_score

tensor([[0.3304, 0.8016, 0.8729],
        [0.0972, 0.5697, 0.4731],
        [0.5991, 0.6128, 0.9207],
        ...,
        [0.8606, 0.8943, 0.8574],
        [0.9947, 0.9849, 0.2182],
        [0.1444, 0.5158, 0.9250]], device='cuda:0')

In [50]:
high_spending_score.shape

torch.Size([499698, 3])

Check the performance all calsulations are running very quick becuase it uses GPU and data on GPU , if you want u can change the data to CPU also 

In [51]:
high_spending_score.to("cpu") # move 500k rows moved to cpu

tensor([[0.3304, 0.8016, 0.8729],
        [0.0972, 0.5697, 0.4731],
        [0.5991, 0.6128, 0.9207],
        ...,
        [0.8606, 0.8943, 0.8574],
        [0.9947, 0.9849, 0.2182],
        [0.1444, 0.5158, 0.9250]])

<h1>Slope </h1>

slope tells us how much something changes when we move forward a little.

<h1> Partial derivative</h1>

A derivative tells us how quickly something is changing at a particular point.



In [55]:
# chicken biryani cost fininding with torch tensor partical derivative
# creating two tensors one is for rice  cost and other for chicken cost 

rice_cost = torch.tensor(50, requires_grad=True,dtype=torch.float32) # rice cost
chicken_cost = torch.tensor(200, requires_grad=True,dtype=torch.float32) # chicken cost

In [56]:
rice_cost

tensor(50., requires_grad=True)

In [57]:
biryani_cost = 3* rice_cost + chicken_cost

In [58]:
print("Total biryani cost:", biryani_cost.item())

Total biryani cost: 350.0


In [59]:
# now find the partial derivative of biryani cost with respect to rice cost and chicken cost

biryani_cost.backward()

In [60]:
print("Partial derivative w.r.t. rice cost:", rice_cost.grad.item())
print("Partial derivative w.r.t. chicken cost:", chicken_cost.grad.item())

Partial derivative w.r.t. rice cost: 3.0
Partial derivative w.r.t. chicken cost: 1.0
